version: "3.9"

services:
  server:
    container_name: ai-server-express
    build:
      context: ./
      target: production
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_DIR=/app/logs
    restart: 'unless-stopped'
    networks:
      - backend

  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge