version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: "unless-stopped"
    networks:
      - backend

  app:
    container_name: ai-server-express
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_DIR=/app/logs
      - SECRET_KEY=secretKey
      - CREDENTIALS=true
      - ORIGIN=*
      - LOG_FORMAT=combined
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge